### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by johnjoo1** [tke578/barchart#3]
I just started getting this today:
```
bash-3.2$ python uoa.py
Traceback (most recent call last):
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/helpers/parser.py", line 17, in get_table_headers
    self.table_headers = self.body.html.find('table thead tr')[0].text.split('\n')[0:15]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uoa.py", line 4, in <module>
    uoa = UOA()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/uoa.py", line 20, in __init__
    self._report                        = self._generate_report()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/uoa.py", line 34, in _generate_report
    init_req = self._initial_request()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/uoa.py", line 50, in _initial_request
    async_req.run()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/helpers/async_request.py", line 70, in run
    run_async.run_until_complete(self.main())
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/asyncio/futures.py", line 175, in result
    raise self._exception
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/helpers/async_request.py", line 50, in main
    await self.make_requests(url)
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/helpers/async_request.py", line 38, in make_requests
    parser.get_table_headers()
  File "/Users/me/anaconda3/envs/test_options/lib/python3.8/site-packages/barchart/helpers/parser.py", line 19, in get_table_headers
    raise ParsingError(msg='Index error on table headers, check response')
barchart.helpers.errors.ParsingError: Parsing error: Index error on table headers, check response
```

I ran it a few times today. I wonder if there's a maximum times that you can run it before Barchart starts shutting you down?

**Comment by johnjoo1** [comment]
This seems to happen sporadically.

**Comment by tke578** [comment]
WIP on parsing error bug https://github.com/tke578/barchart/pull/6 @johnjoo1

**Comment by tke578** [comment]
closed via https://github.com/tke578/barchart/pull/6 @johnjoo1
